title: "ExoDoxa"
email: lilsandro20000@gmail.com
description: "Mi narrativa viva"

github_username: "ExoDoxa"
minimal_mistakes_skin: dark
search: true

# Configuración de construcción
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

# Configuración de salida
permalink: /:categories/:title/
paginate: 5 # Cantidad de publicaciones por página
paginate_path: /pagina:num/
timezone: America/Bogota

include:
  - _pages

# Plugins necesarios para Jekyll
plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Información del autor
author:
  name   : "ExoDoxa"
  avatar : "/assets/images/Foto-bio.jpg"
  bio    : "Mi narrativa viva"
  links:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/lis_4ndru/"
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/@Exodoxa"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ExoDoxa"

footer:
  links:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/lis_4ndru/"
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/@Exodoxa"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ExoDoxa"

# Configuración para organizar archivos
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      Comentarios: true
      Compartir: true
      Relacionados: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true


# Archivos de categorías y etiquetas

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: archive
  permalinks:
    category: '/categorias/:name/'
    tag: '/etiquetas/:name/'

categorias_archive:
  type: liquid
  path: /categorias/
tag_archive:
  type: liquid
  path: /etiquetas/
